-- 코드를 입력하세요
-- 생산일자가 2022년 5월인 식품들의
-- PRODUCT_ID	PRODUCT_NAME	TOTAL_SALES 조회
-- TOTAL_SALES 기준 내림차순 , 식품 ID 오름차순


SELECT A.PRODUCT_ID AS PRODUCT_ID, A.PRODUCT_NAME AS PRODUCT_NAME
, SUM(B.AMOUNT * A.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT A 
JOIN FOOD_ORDER B ON A.PRODUCT_ID = B.PRODUCT_ID 
WHERE PRODUCE_DATE LIKE "2022-05%"
GROUP BY A.PRODUCT_ID 
ORDER BY TOTAL_SALES DESC , A.PRODUCT_ID 
