-- 코드를 입력하세요
-- 식품분류별로 가격이 제일 비싼 식품의 
-- 분류, 가격 , 이름 
-- 분류는 과자, 국, 김치, 식용유 
-- 식품 가격 기준 내림차순 

SELECT A.CATEGORY AS CATEGORY, B.PRICE AS PRICE , A.PRODUCT_NAME AS PRODUCT_NAME
FROM FOOD_PRODUCT A 
JOIN ( SELECT CATEGORY, MAX(PRICE) AS PRICE , PRODUCT_NAME 
FROM FOOD_PRODUCT 
GROUP BY CATEGORY
HAVING CATEGORY IN ("과자" , "국" , "김치" , "식용유") ) B 
ON A.PRICE = B.PRICE AND A.CATEGORY = B.CATEGORY 
ORDER BY PRICE DESC